name: Changelog Update
description: Updating the Changelog file

inputs:
  version:
    description: 'The version e.g. 9.5.1-202507150815-191-270e262'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update Changelog
      shell: bash
      run: |
        ${{ github.action_path }}/updateChangelog.sh "${{ inputs.version }}"
