name: Main Pipeline
run-name: 'Main build workflow #${{ github.run_number }} triggered by ${{ github.actor }} on ${{ github.ref }}'

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"  # Runs at 02:00 UTC every day
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        description: 'Deploy to development environment'
        required: true
        type: boolean
        default: true
      update_archetype:
        description: 'Whether to update the uniport archetype or not'
        required: true
        type: boolean
        default: true

# Prevent running builds for the same branch in parallel
# New workflows will cancel existing workflows…
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (main)
    uses: ./.github/workflows/build.yml
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
      NEXUS_NPM_TOKEN_WRITE: ${{ secrets.NEXUS_NPM_TOKEN_WRITE }}
      NEXUS_NPM_TOKEN_READ_ONLY: ${{ secrets.NEXUS_NPM_TOKEN_READ_ONLY }}
      MACDUFF_KEYCHAIN_PASSWORD: ${{ secrets.MACDUFF_KEYCHAIN_PASSWORD }}

  deploy:
    name: Trigger Deployment (dev)
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || inputs.deploy_to_dev }}
    needs: [build]
    uses: uniport/workflows/.github/workflows/deploy-dev.yml@main
    with:
      version: ${{ needs.build.outputs.VERSION }}
      component_name: base
    secrets:
      UNIPORT_APP_PRIVATE_KEY: ${{ secrets.UNIPORT_APP_PRIVATE_KEY }}

  archetype:
    name: Update Archetype
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || inputs.update_archetype }}
    needs: [build]
    uses: uniport/workflows/.github/workflows/update-archetype.yml@main
    with:
      version: ${{ needs.build.outputs.VERSION }}
      component_name: base
    secrets:
      UNIPORT_APP_PRIVATE_KEY: ${{ secrets.UNIPORT_APP_PRIVATE_KEY }}

  tag:
    name: Nexus Tagging
    needs: [build]
    uses: uniport/workflows/.github/workflows/tag-nexus-artifacts.yml@main
    with:
      version: ${{ needs.build.outputs.VERSION }}
      group_id: ${{ needs.build.outputs.GROUP_ID }}
      tag_docker: true
      tag_npm: true
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
