name: 'Setup Helm repositories'
description: 'Sets up Helm repositories'
inputs:
  repositories:
    description: 'A JSON list of Helm repository objects with `name` and `url` keys.'
    required: false
    default: |
      [
        {
          "name": "inventage-portal-helm",
          "url": "https://nexus3.inventage.com/repository/inventage-portal-helm/"
        },
        {
          "name": "inventage-portal-helm-staging",
          "url": "https://nexus3.inventage.com/repository/inventage-portal-helm-staging/"
        }
      ]
  username:
    description: 'The username for accessing Helm repositories'
  password:
    description: 'The password for accessing Helm repositories'

runs:
  using: 'composite'
  steps:
    - name: Add Helm repositories
      shell: bash
      if: ${{ inputs.repositories != '[]' }}
      run: |
        echo '${{ inputs.repositories }}' | jq -c '.[]' | while IFS= read -r repo_json; do
          repo_name=$(echo "$repo_json" | jq -r .name)
          repo_url=$(echo "$repo_json" | jq -r .url)
          echo "Repo name: $repo_name"
          echo "Repo URL: $repo_url"
        done
