name: Ensure Branch
description: Checks if a branch exists in the repo and aborts otherwise

inputs:
  branch:
    description: 'Branch name to check'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 # Fetch only the latest commit
        ref: ${{ github.ref }}

    - name: Check if branch exists
      id: branch_check
      run: |
        if [[ -n $(git ls-remote --heads origin ${{ inputs.branch }}) ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
        else
            echo "exists=false" >> $GITHUB_OUTPUT          
        fi
      shell: bash

    - name: Branch exists
      if: steps.branch_check.outputs.exists == 'true'
      shell: bash
      run: |
        echo "Branch '${{ inputs.branch }}' exists!"

    - name: Branch does NOT exists
      if: steps.branch_check.outputs.exists == 'false'
      shell: bash
      run: |
        echo "Branch '${{ inputs.branch }}' does NOT exist. Aborting..."
        exit 1
