# Workflow for moving docker images in Nexus3 (multi-arch)
name: Docker Images Move

on:
  workflow_call:
    secrets:
      NEXUS3_PW:
        required: true
    inputs:
      tag:
        description: 'The tag name associated with docker images to move'
        type: string
        required: true
      source_registry:
        description: 'The source registry to move the docker images from'
        type: string
        required: true
      target_registry:
        description: 'The target registry to move the docker images to'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name associated with docker images to move'
        type: string
        required: true
      source_registry:
        description: 'The source registry to move the docker images from'
        type: string
        required: true
      target_registry:
        description: 'The target registry to move the docker images to'
        type: string
        required: true

jobs:
  move:
    name: Docker Images Move
    runs-on: ubuntu-latest
    steps:
      - name: Move docker images
        uses: uniport/workflows/.github/actions/release-docker-images@main
        with:
          tag: ${{ inputs.tag }}
          source_registry: ${{ inputs.source_registry }}
          target_registry: ${{ inputs.target_registry }}
          nexus3_url: ${{ vars.NEXUS3_URL }}
          nexus3_user: ${{ vars.NEXUS3_USER }}
          nexus3_password: ${{ secrets.NEXUS3_PW }}
