# Workflow for creating a patch branch
name: Git Patch Branch Create

on:
  workflow_call:
    inputs:
      major:
        description: "The major version in SemVer"
        type: string
        required: true
      minor:
        description: "The minor version in SemVer"
        type: string
        required: true
      patch:
        description: "The patch version in SemVer"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      major:
        description: "The major version in SemVer"
        type: string
        required: true
      minor:
        description: "The minor version in SemVer"
        type: string
        required: true
      patch:
        description: "The patch version in SemVer"
        type: string
        required: true

jobs:
  create:
    name: Patch Branch Create
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          PATCH_BRANCH_NAME="${{ inputs.major }}.${{ inputs.minor }}.x"

          cat >> $GITHUB_OUTPUT <<EOF  
          PATCH_BRANCH_NAME=$PATCH_BRANCH_NAME
          EOF

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch only the latest commit

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create patch branch
        if: ${{ inputs.patch }} != "0"
        shell: bash
        run: |
          git checkout -B "${{ steps.setup.outputs.PATCH_BRANCH_NAME }}"
          git push origin "${{ steps.setup.outputs.PATCH_BRANCH_NAME }}"
          git checkout -

      - name: Summary
        shell: bash
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF  
          ## Setup
          ### Inputs
          - **major**: \`${{ inputs.major }}\`          
          - **minor**: \`${{ inputs.minor }}\`          
          - **patch**: \`${{ inputs.patch }}\`          
          ### Outputs
          - **PATCH_BRANCH_NAME**: \`${{ steps.setup.outputs.PATCH_BRANCH_NAME }}\`
          EOF
