# Workflow for doing a jira release
name: Jira Release

on:
  workflow_call:
    secrets:
      ATLASSIAN_AUTH_PSW:
        required: true
    inputs:
      version:
        description: 'The version e.g. 9.5.1-202507150815-191-270e262'
        type: string
        required: true
      semver:
        description: 'The SemVer e.g. 9.5.1'
        type: string
        required: true
      component_name:
        description: 'The component name to release'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: 'The version e.g. 9.5.1-202507150815-191-270e262'
        type: string
        required: true
      semver:
        description: 'The SemVer e.g. 9.5.1'
        type: string
        required: true
      component_name:
        description: 'The component name to release'
        type: string
        required: true

jobs:
  move:
    name: Jira Release
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        uses: uniport/workflows/.github/actions/validate-version@main
        with:
          version: ${{ inputs.version }}

      - name: Setup
        id: setup
        shell: bash
        run: |
          AUTH_STRING="${{ vars.ATLASSIAN_AUTH_USR }}:${{ secrets.ATLASSIAN_AUTH_PSW }}"

          JIRA_BASIC_AUTH_TOKEN=$(echo -n "$AUTH_STRING" | base64 -w0 -)

          cat >> $GITHUB_OUTPUT <<EOF
          JIRA_BASIC_AUTH_TOKEN=$JIRA_BASIC_AUTH_TOKEN
          EOF

      - name: Release Jira
        uses: uniport/workflows/.github/actions/release-jira@main
        with:
          component_name: ${{ inputs.component_name }}
          semver: ${{ inputs.semver }}
          version: ${{ inputs.version }}
          jira_basic_auth_token: ${{ steps.setup.outputs.JIRA_BASIC_AUTH_TOKEN }}
