name: Nexus Tag Search
run-name: 'Nexus search tag workflow #${{ github.run_number }} triggered by ${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name to search for'
        type: string
        required: true

env:
  NEXUS3_URL: ${{ vars.NEXUS3_URL }}
  NEXUS3_USER: ${{ vars.NEXUS3_USER }}

jobs:
  search:
    name: Tag Search
    runs-on: ubuntu-latest
    steps:
      # https://help.sonatype.com/en/tagging.html
      - name: Search Components with Nexus Tag
        run: |
          curl -fSs -X GET \
          -u '${{ env.NEXUS3_USER }}:${{ secrets.NEXUS3_PW }}' \
          '${{ env.NEXUS3_URL }}/service/rest/v1/search?tag="${{ inputs.tag }}"'
