# Workflow for associating components that belong to a Nexus tag
name: Nexus Tag Associate
run-name: 'Nexus associate tag workflow #${{ github.run_number }} triggered by ${{ github.actor }}'

on:
  workflow_call:
    secrets:
      NEXUS3_PW:
        required: true
    inputs:
      repo_id:
        description: 'The ID of the Nexus repository to search for'
        type: string
        required: true
      version:
        description: 'The version of the components to search for'
        type: string
        required: true
      tag_name:
        description: 'The name of the tag to associate the components with'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repo_id:
        description: 'The ID of the Nexus repository to search for'
        type: string
        required: true
      version:
        description: 'The version of the components to search for'
        type: string
        required: true
      tag_name:
        description: 'The name of the tag to associate the components with'
        type: string
        required: true

env:
  NEXUS3_URL: ${{ vars.NEXUS3_URL }}
  NEXUS3_USER: ${{ vars.NEXUS3_USER }}

# To associate a tag with components, the components are search based on the repository and version
# The repository is searched for an EXACT match (surrounded by quotes)
# The version supports all supported search patterns as provided by nexus i.e. wildcards, tokens and exact matches
# See: https://help.sonatype.com/en/searching-for-components.html#keyword-search-query-string
jobs:
  associate:
    name: Tag Associate
    runs-on: ubuntu-latest
    steps:
      # https://help.sonatype.com/en/tagging.html
      - name: Associate Components with Nexus Tag
        run: |
          curl -fSs -X POST \
          -u '${{ env.NEXUS3_USER }}:${{ secrets.NEXUS3_PW }}' \
          '${{ env.NEXUS3_URL }}/service/rest/v1/tags/associate/${{ inputs.tag_name }}?repository="${{ inputs.repo_id }}"&version=${{ inputs.version }}'
