# Workflow for searching components that belong to a Nexus tag
name: Nexus Tag Search
run-name: 'Nexus search tag workflow #${{ github.run_number }} triggered by ${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name to search for'
        type: string
        required: true

env:
  NEXUS3_URL: ${{ vars.NEXUS3_URL }}
  NEXUS3_USER: ${{ vars.NEXUS3_USER }}

jobs:
  search:
    name: Tag Search
    runs-on: ubuntu-latest
    steps:
      # https://help.sonatype.com/en/tagging.html
      - name: Search Components with Nexus Tag
        env:
          NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
          TAG: ${{ inputs.tag }}
        run: |
          curl -fSs -X GET \
          --user "$NEXUS3_USER:$NEXUS3_PW" \
          "$NEXUS3_URL/service/rest/v1/search?tag=\"$TAG\""
