# Runs NPM the `lint` command defined in `package.json` to ensure code quality and adherence to coding standards.
name: NPM Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.ref }}

      - uses: uniport/workflows/.github/actions/setup-node-and-dependencies@main

      - name: Linters
        run: npm run lint
