# Runs NPM the `lint` command defined in `package.json` to ensure code quality and adherence to coding standards.
name: NPM Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: uniport/workflows/.github/actions/setup-node-and-dependencies@main

      - name: Linters
        run: npm run lint
