name: '[Test] Maven Build'
run-name: '[Test] Maven build #${{ github.run_number }} triggered by ${{ github.actor }} on ${{ github.ref }}'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup-maven-build-variables.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Setup Helm
        uses: ./.github/actions/add-helm-repositories
        with:
          username: ${{ vars.NEXUS3_USER }}
          password: ${{ secrets.NEXUS3_PW }}

      - name: Set version
        run: |
          mvn -B --no-transfer-progress build-helper:parse-version versions:set -DnewVersion=${{ needs.setup.outputs.RC_VERSION }} -DoldVersion=* -DgroupId=* -DartifactId=* -DgenerateBackupPoms=false

      - name: Maven build
        run: |
          mvn -B -V --no-transfer-progress --update-snapshots -P!local,ci -DmultiArchBuild=true verify
