name: '[Test] Validate Version'
run-name: '[Test] Validating version ${{ inputs.version }} using shared action'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to validate'
        type: string
        required: true

jobs:
  validate:
    name: Validate Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Validate Version
        uses: ./.github/actions/validate-version
        with:
          version: ${{ inputs.version }}
