name: Update Archetype
run-name: 'Update archetype #${{ github.run_number }} triggered by ${{ github.actor }}'

on:
  workflow_call:
    secrets:
      UNIPORT_APP_PRIVATE_KEY:
        required: true
    inputs:
      version:
        description: 'The version to register'
        type: string
        required: true
      component_name:
        description: 'Portal component name to update its version in the deployment repository'
        required: true
        type: string
      command:
        description: 'The command to use in the registerVersion.sh script'
        type: string
        default: 'snapshot'
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to register'
        type: string
        required: true
      component_name:
        description: 'Portal component name to update its version in the deployment repository'
        required: true
        type: string
      command:
        description: 'The command to use in the registerVersion.sh script'
        type: choice
        required: true
        default: 'snapshot'
        options:
          - 'snapshot'
          - 'release'

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        uses: uniport/workflows/.github/actions/validate-version@main
        with:
          version: ${{ inputs.version }}

      # Generate a token for the Uniport GitHub App
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.UNIPORT_APP_ID }}
          private-key: ${{ secrets.UNIPORT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            archetype-inventage-portal-solution

      - name: Checkout archetype repo
        uses: actions/checkout@v4
        with:
          repository: uniport/archetype-inventage-portal-solution
          token: ${{ steps.app-token.outputs.token }}
          ref: master
          path: archetype-repo

      - name: Configure Git user
        run: |
          cd archetype-repo
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Register version
        run: |
          cd archetype-repo
          ./registerVersion.sh ${{ inputs.command }} "${{ inputs.component_name }}" ${{ inputs.version }}
          git push origin master
